### ISSUE TITLE
Scapy Fails to Execute

### ISSUE THREAD

**Issue by darksheer** [Homebrew/homebrew-python#210]
Executing Scapy fails. 

```
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 25, in <module>
    interact()
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/main.py", line 278, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/all.py", line 25, in <module>
    from route import *
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/route.py", line 162, in <module>
    conf.route=Route()
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/route.py", line 22, in __init__
    self.resync()
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/unix.py", line 86, in read_routes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/__init__.py", line 36, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
  File "/usr/local/lib/python2.7/site-packages/scapy_real-2.2.0.dev0-py2.7.egg/scapy/arch/pcapdnet.py", line 187, in get_if_raw_addr
    i = dnet.intf()
AttributeError: 'module' object has no attribute 'intf'

```

Brew Config

```
ORIGIN: https://github.com/Homebrew/homebrew
HEAD: 1ebb60b6e5762beb26cfb62a8a1f4ef1692f6540
Last commit: 14 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: dual-core 64-bit sandybridge
OS X: 10.10.2-x86_64
Xcode: 6.2
CLT: 6.2.0.0.1.1424975374
couldn't understand kern.osversion `14.1.0'
GCC-4.2: build 5666
Clang: 6.0 build 600
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby
Java: 1.8.0_40
```

**Comment by darksheer** [comment]
Tried a number of work arounds suggested on the interwebz based on the error output.  Still nothing working...

**Comment by darksheer** [comment]
Still getting the same errors when executing Scapy after a fresh test & install of homebrew.

**Comment by tdsmith** [comment]
Please run `brew update && brew reinstall scapy` and provide the output of `brew gist-logs scapy` and whatever error you're seeing in a new ticket. Thanks!

**Comment by darksheer** [comment]
@tdsmith Done and creating new ticket.
