### ISSUE TITLE
scapy run "Device not configured"

### ISSUE THREAD

**Issue by amosshapira** [Homebrew/homebrew-python#256]
After install scapy 2.3.1 on OSX Yosemite 10.10.5 with Python 2.7.10, executing "scapy" comes up with error:
```
$ scapy
INFO: Can't import python gnuplot wrapper . Won't be able to plot.
INFO: Can't import PyX. Won't be able to use psdump() or pdfdump().
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 25, in <module>
    interact()
  File "/usr/local/lib/python2.7/site-packages/scapy/main.py", line 278, in interact
    scapy_builtins = __import__("all",globals(),locals(),".").__dict__
  File "/usr/local/lib/python2.7/site-packages/scapy/all.py", line 25, in <module>
    from route import *
  File "/usr/local/lib/python2.7/site-packages/scapy/route.py", line 162, in <module>
    conf.route=Route()
  File "/usr/local/lib/python2.7/site-packages/scapy/route.py", line 22, in __init__
    self.resync()
  File "/usr/local/lib/python2.7/site-packages/scapy/route.py", line 31, in resync
    self.routes = read_routes()
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/unix.py", line 86, in read_routes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/__init__.py", line 36, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
  File "/usr/local/lib/python2.7/site-packages/scapy/arch/pcapdnet.py", line 201, in get_if_raw_addr
    return i.get(ifname)["addr"].data
  File "dnet.pyx", line 990, in dnet.intf.get
OSError: Device not configured
```
I found some mention that perhaps it has something to do with VirtualBox' network (I have VirtualBox 5.0.2 installed on the system), but I couldn't find the file to implement a manual patch to work around this.

**Comment by tdsmith** [comment]
I can't reproduce this; please consider filing against scapy.
