### ISSUE TITLE
problem installing homebrew-python

### ISSUE THREAD

**Issue by francispoulin** [Homebrew/homebrew-python#261]
I have just installed homebrew-python on my laptop and that seems to run ok.  However, when I try updating numpy I get the following problem (see below).

I think this is because when I was updating libraries using the default version of python I was using sudo.  Now brew can't change this because of permissions.

I suspect that I have to remove those but wanted to ask in case someone had some better advice.

Sorry for the bother.

 /usr/local/bin/pip2 install --upgrade numpy
Collecting numpy
  Using cached numpy-1.10.1-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Installing collected packages: numpy
  Found existing installation: numpy 1.8.2
    Uninstalling numpy-1.8.2:
      Successfully uninstalled numpy-1.8.2
  Rolling back uninstall of numpy
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 311, in run
    root=options.root_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 646, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 803, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 998, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 371, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 317, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/usr/local/bin/f2py'

**Comment by tdsmith** [comment]
The simplest thing to do is to run `chown -R "$USER" /usr/local`.

**Comment by francispoulin** [comment]
Thank you.  That was a clean fix.

If I have the error below should I do the same thing to /Library/Python?

OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/pytz-2015.4.dist-info/DESCRIPTION.rst'

**Comment by tdsmith** [comment]
If you want to be able to install packages into /Library/Python without using sudo, then yes, that should be safe. (An alternative is to just delete the packages from /Library/Python, either using `rm` or by running `sudo pip uninstall` – you may have to run uninstall more than once if the packages are installed to more than one place.)

**Comment by francispoulin** [comment]
Thank you.  I did the sudo pip uninstall and that worked nicely.
