### ISSUE TITLE
Using OpenBLAS breaks Numpy

### ISSUE THREAD

**Issue by jakobmoss** [Homebrew/homebrew-python#305]
Using the option `--with-openblas` when installing Numpy makes me unable to use it. It installs just fine, but I cannot import it (I am using brewed Python):
```
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/local/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/numpy/core/multiarray.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /usr/local/lib/python2.7/site-packages/numpy/core/multiarray.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/numpy/core/multiarray.so
```

Without this option (i.e. using the standard Accelerate Framework) everything works fine. I have tried with OpenBLAS built from source (with and without the `--with-openmp` option) and from bottle.

I suspect, that he problem could be a failure in the linking. As far as I can tell, Numpy is not linked against openblas:
```
> otool -L multiarray.so
multiarray.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

OpenBLAS seems to be correctly linked against the appropriate gcc-libraries (the missing symbol from Numpy's error is contained in `libgomp.dylib`):
```
> otool -L libopenblas_haswellp-r0.2.18.dylib
libopenblas_haswellp-r0.2.18.dylib:
	/usr/local/opt/openblas/lib/libopenblas_haswellp-r0.2.18.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/local/opt/gcc/lib/gcc/6/libgomp.1.dylib (compatibility version 2.0.0, current version 2.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/usr/local/opt/gcc/lib/gcc/6/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/lib/gcc/6/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

Running `brew doctor` returns no errors and the output from `brew config` is:
```
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: e9cc2a5d88da6d1719763a26c1fc455c51e2c3db
Last commit: 12 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 39771d221172393741c7bc117dce0816d5ece50b
Core tap last commit: 11 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Clang: 7.3 build 703
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
System Ruby: 2.0.0-p648
OS X: 10.11.5-x86_64
Xcode: N/A
CLT: 7.3.1.0.1.1461711523
X11: 2.7.9 => /opt/X11
```

EDIT: The linking when using Accelerate (numpy built from source):
```
> otool -L multiarray.so
multiarray.so:
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by jakobmoss** [comment]
The problem is solved now. It must somehow have been connected to OpenBLAS. After the release of a revision of the OpenBLAS formula (https://github.com/Homebrew/homebrew-science/commit/c2722f4b695d58c7b250575dcb03e222ea18b0ae) I tried again and things are fine now.

I still find it strange, however, since Numpy is linking against the file which also existed before:
"""
> otool -L multiarray.so
multiarray.so:
	/usr/local/opt/openblas/lib/libopenblas_haswellp-r0.2.18.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
"""
