### ISSUE TITLE
numpy fails to build with openblas option

### ISSUE THREAD

**Issue by jeslago** [Homebrew/homebrew-python#359]
I am trying to install numpy with openblas. Using 

`brew install numpy --with-openblas`

Returns the following error:

```
==> Installing numpy from homebrew/python
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://files.pythonhosted.org/packages/16/f5/b432f028134dd30cfbf6f21b8264a9938e5e0f75204e72453af08d67eb0b
Already downloaded: /Users/jesus/Library/Caches/Homebrew/numpy-1.11.2.tar.gz
==> Downloading https://pypi.python.org/packages/source/n/nose/nose-1.3.7.tar.gz
Already downloaded: /Users/jesus/Library/Caches/Homebrew/numpy--nose-1.3.7.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/numpy/1.11.2/libexec/nose --single-ver
==> python setup.py build --fcompiler=gnu95 --parallel=8 install --prefix=/usr/local/Cellar/numpy/1.11.2 --single-version-
==> python -c import numpy; assert numpy.test().wasSuccessful()
Last 15 lines from /Users/jesus/Library/Logs/Homebrew/numpy/03.python:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>

    from numpy.lib import add_newdoc
  File "/usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: dlopen(/usr/local/Cellar/numpy/1.11.2/lib/python2.7/site-packages/numpy/core/multiarray.so, 2):
 Library not loaded: /usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/opt/openblas/lib/libopenblas_haswellp-r0.2.18.dylib
  Reason: image not found
```

I have gcc6 installed. I tried to install gcc5 to see if the problem would solve, but it doesn't, as gcc5 can not install in the standard path due to the current gcc6 installation.

Any ideas of what can I do?

Thank you for the help.

**Comment by tdsmith** [comment]
Try `brew reinstall openblas -s` first.

**Comment by jeslago** [comment]
Thanks a lot for the help. It worked.

What was the problem? Was it that I had to build openblas from source in order to get the right path to the gcc compiler?

**Comment by tdsmith** [comment]
Yes, the openblas bottle was stale.
